export const routes = {
  home: "/",
  reserva: "/reservas",
  about: "/about",
  Register: "/register",
  Login: "/login",
  administracion: "/administracion",
  Reservas: "/bookings",
  productos: '/administracion/productos',
  permisos: '/administracion/permisos',
  categorias: '/administracion/categorias',
  caracteristicas: '/administracion/caracteristicas',
  productList: '/product-list',
  resultados: '/resultados',
};
